export enum QueryKeys {
  INFINITY_POPULAR = 'INFINITY_POPULAR',
  INFINITY_TRENDING = 'INFINITY_TRENDING',
  INFINITY_RECOMMENDATIONS = 'INFINITY_RECOMMENDATIONS',
  INFINITY_UPCOMING = 'INFINITY_UPCOMING',
  INFINITY_TOP_RATED = 'INFINITY_TOP_RATED',
}
